runtime: nodejs20
env: standard

handlers:
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
    require_matching_file: false

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
